apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app
  namespace: monitoring 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
      - name: example-app
        image: quay.io/manojdhanorkar/prometheus-golang:0.0.6
        ports:
        - name: web
          containerPort: 8080
